### ISSUE TITLE
Set up a mechanism to collect weekly feedback

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#10]
My typical approach is the "sticky note" method. I pass around two different colored post-it/stick notes and ask them to write one or more comments explaining what they liked/learned/gained on one color and one or more comments explaining improvements/misunderstandings/complaints on the other color. I do this weekly and make a quick assessment on what might need reinforcement in next lectures and whether to slow down or speed up.

I've seen this done in a hackpad also. You can open a hackpad (or similar collaborative writing tool) and have two sections where students type these things collectively. This can be done in a few minutes.

We could do this at the start of work sessions in some way or I can do it via brightspace.

**Comment by moorepants** [comment]
I learned that MS Teams has a "whiteboard" that you can literally create virtual post it notes and collaboratively arrange them on the board. This could recreate what I do manually in a classroom.

**Comment by zofiatycz** [comment]
I created a test whiteboard on the instructors' channel on the MS Teams. It needs to be tested if everyone can edit it. I couldn't find an option to save the template, so I think it will be easier to save/export it every week and clean existing one

**Comment by moorepants** [comment]
I edited it. Check it out.

**Comment by zofiatycz** [comment]
Should I add a whiteboard to the main course channel?

**Comment by moorepants** [comment]
Yes, please do. Maybe include a note that says something like "This whiteboard will be used during the work sessions, please wait to the work session to add your comments."

**Comment by zofiatycz** [comment]
done
