### ISSUE TITLE
Review the course website before sharing with students

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#13]
@akshath03, @zofiatycz, Rosanne, and Domas

I have a final draft of the course website up here:

https://moorepants.github.io/me41055/

Can you all carefully read the three pages and reply here with any feedback on the clarity and completeness of the information? You can also read the panel feedback in #5 and see if my version of the course address things there (or introduces likely new issues). I also would like feedback on the academic integrity part, in particular. I thought about this and wonder your takes on how we will handle direct copying of homework solutions.

Please check this over in the next couple of days.

**Comment by zofiatycz** [comment]
About academic integrity, rules are quite clear. However, it is not clear to me what to do with the example solution posted from the previous week, can it be used to solve problem student didn't cope with? The second remark is that last year using the help from other students was possible if it was clearly written who and to what extent helped with the code.

The content of the course is clear, as is the schedule of work. 

There is the word repetition in the Vocareum part ("edit" is doubled)

**Comment by akshath03** [comment]
In the assignments and grades section, it is not clear whether the students are supposed to submit individually if they are working in a pair or a single submission for the pair. I would suggest to submit individually which eases the process of grading and also for plagiarism checks.

**Comment by moorepants** [comment]
> However, it is not clear to me what to do with the example solution posted from the previous week, can it be used to solve problem student didn't cope with?

If we share a solution (ours or one of the student submissions), those are free to use in any way they want after it is shared. The subsequent homeworks should not rely on the solutions to specific problems from the prior week (maybe that is what you are implying?)

> The second remark is that last year using the help from other students was possible if it was clearly written who and to what extent helped with the code.

My current plan is to require a "contribution statement" for students that submit the homework as a pair. That statement should explain who did what in that homework. For individual submissions, no statement is required. For all submissions (individual or pair) the code and solution has to be unique with respect to other student submissions as well as any existing materials students find (notebooks online, solutions online, past homeworks).

I can change this plan to make all students write a custom "contribution statement". This would require them to document any help they received in completing the assignment. Maybe that's simpler.

>  thought about this and wonder your takes on how we will handle direct copying of homework solutions.

Ideally we figure out how to run automated plagiarism detection on the submissions. If we can figure that out, I may have you all scan through a random subset of submissions manually to detect plagiarism.

**Comment by moorepants** [comment]
> I would suggest to submit individually which eases the process of grading and also for plagiarism checks.

I could have every student submit the notebook. If they are working in a pair, then those notebooks could be identical copies of each other. Given @zofiatycz's suggestion, I could have each individual student write their custom contribution statement whether submitted as a pair or individual, i.e. we get unique contribution statements from every student, but solutions can be identical with their submission partner.

**Comment by moorepants** [comment]
Some feedback from a student from last year:

General notes:
- I’m personally not familiar with Vocareum (I think) if that is the case for other students you
might have to explain what that is during the course

- You will probably include this elsewhere, but it would be nice to have an overview of the
deadlines for the course. This means when to hand in which homework and when the
deadline for reviewing this homework is

Specific notes:
@ Time and Location, in the last paragraph; “you must self sign up” seems like a bit of odd phrasing.
(not entirely sure if you wanted feedback on stuff like this too).

@Assignment & grades, in the first paragraph; I would add “homework grade or IF you are taking a
resit exam”

**Comment by moorepants** [comment]
One more: make sure the front page points them to the schedule page, as it seems people aren't seeing the other pages on the website.

**Comment by moorepants** [comment]
The draft notification is now removed and the brightspace page is active.
