### ISSUE TITLE
Review the Jupyter and Python lecture notes page

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#24]
I have a first draft of:

https://moorepants.github.io/learn-multibody-dynamics/jupyter-python.html

It needs a look over for details. Feel free to open a pull request to improve this file: 

https://github.com/moorepants/learn-multibody-dynamics/blob/master/jupyter-python.rst

**Comment by moorepants** [comment]
Final draft is live.

**Comment by moorepants** [comment]
Thanks. I'll change the `%paste` example to something else.

**Comment by akshath03** [comment]
The examples in this page with hyperlinks for every concept for example lists, tuples and dictionaries are useful and clear. In the introduction of Jupyter notebook should we specifically mention to install anaconda for people working in windows?

**Comment by moorepants** [comment]
I think I need an install page added to the notes. Just haven't gotten around to it. The course website has some install instructions.

I think that I want to suggest installing miniconda instead of anaconda and then to configure to install from conda forge. This mimics what I personally do.

**Comment by moorepants** [comment]
@akshath03 Can you try out these instructions and tell me if it works for you: https://moorepants.github.io/learn-multibody-dynamics/install.html

It would be nice to try on WIndows and Mac by you all, because I am on Linux and can't test the other OS's.

**Comment by akshath03** [comment]
Yes, I already tried running jupyter notebook from this link. I think both are similar and works fine.

https://moorepants.github.io/me41055/software.html

**Comment by moorepants** [comment]
One thing I was worried about is whether the `conda update --all` is extremely slow in Anaconda vs Miniconda. If you add the conda forge channel to an anaconda install and then run update all, it basically has to uninstall all the anaconda packages and download new versions from conda forge. Anyone experience that?

**Comment by moorepants** [comment]
Calling this one done!
