### ISSUE TITLE
Review the SymPy lecture notes page

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#25]
I have a first draft of:

https://moorepants.github.io/learn-multibody-dynamics/sympy.html

It needs a look over for details. Feel free to open a pull request to improve this file:

https://github.com/moorepants/learn-multibody-dynamics/blob/master/sympy.rst

**Comment by moorepants** [comment]
Final draft is live.

**Comment by zofiatycz** [comment]
Everything it's clear and working correctly
The only probably not important remark is that one box in warnings in differentiating section is shifted to the right

**Comment by moorepants** [comment]
>  The only probably not important remark is that one box in warnings in differentiating section is shifted to the right

Yeh, I noticed that too. It is some issue in the css between the theme and the jupyter-sphinx. Maybe I just need to avoid code cells in the warning/note boxes for now.

Interestingly this is what it looks like on the live website:
![image](https://user-images.githubusercontent.com/276007/151873536-f28e5564-39d3-42c6-9963-ab8465c6213b.png)

But it looks fine locally on my computer as I'm developing it:
![image](https://user-images.githubusercontent.com/276007/151873598-8c9e2ccc-ddb5-40cc-865c-7da6358b9853.png)

I'll have to dig into the css to figure out why it is different on the live version.

**Comment by akshath03** [comment]
![image](https://user-images.githubusercontent.com/97916843/152209687-859b544a-3582-40fc-9d22-12e51c0473fb.png)

Is it possible to fit the decimal places inside the box or is it an error like the above issue?

**Comment by moorepants** [comment]
Gonna leave this one as is and call it done.
