### ISSUE TITLE
Review the orientation and reference frame page

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#26]
https://moorepants.github.io/learn-multibody-dynamics/orientation.html

**Comment by moorepants** [comment]
Final draft is live.

**Comment by zofiatycz** [comment]
The only remark is that in fig.8 the d.z axis is longer than c.z, because of that it looks a bit like a 3-d drawing and the rotation is done around the d.x axis. After a moment it's clear, but it took me a fair moment to see it correctly. 

Notebook works without any problems.

**Comment by moorepants** [comment]
Ok, I'll see if I can adjust the figure. It was hard to draw because the picture is in perspective. I plan to walk through it and make some live drawings in the lecture video, so that would help clear things. Great feedback!

**Comment by moorepants** [comment]
This is live and done.
