### ISSUE TITLE
Update software installation notes to include numpy, scipy, pythreejs, scikits.odes, etc.

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#47]
We'll soon need these in the course.

**Comment by akshath03** [comment]
Finally I made test cases and found only two errors/problems with the packages. 
 
- The animation extension for pyThreejs is still not enabled and no animation is displayed in the notebook.
- The scikit.odes package is installed but the solvers are missing from the dae package I guess and throws the following error.
            ValueError: Integrator name ida does not exsist

The matplotlib and ipywidgets animation work as expected. All these packages are working as expected in the student view as well. The autograder over these notebooks does'nt throw any error and looks good.

**Comment by moorepants** [comment]
For the autograder tests, did you just make sure they import or did you try to test some code?

**Comment by moorepants** [comment]
Last year numpy, scipy, and scikits.odes were install. PyThreeJS never worked.
