### ISSUE TITLE
Term left out in generalized inertia torque in Nonholomic constraints chapter

### ISSUE THREAD

**Issue by TJStienstra** [moorepants/me41055#52]
Saw someone else pointing out the problem that in the chapter about `Equations of Motion with Nonholonomic Constraints` step 8 a term was left out when computing the generalized inertia torques.
```py
Ts_A = -A.ang_acc_in(N).dot(I_A_Ao)
Ts_B = -B.ang_acc_in(N).dot(I_B_Bo)
Ts_C = -C.ang_acc_in(N).dot(I_C_Co)
```
Should be:
```py
Ts_A = -A.ang_acc_in(N).dot(I_A_Ao) + me.cross(A.ang_vel_in(N), I_A_Ao).dot(A.ang_vel_in(N))
Ts_B = -B.ang_acc_in(N).dot(I_B_Bo) + me.cross(B.ang_vel_in(N), I_B_Bo).dot(B.ang_vel_in(N))
Ts_C = -C.ang_acc_in(N).dot(I_C_Co) + me.cross(C.ang_vel_in(N), I_C_Co).dot(C.ang_vel_in(N))
```
This term should also be added in the next block where the $\ddot{q}$'s are replaced.

**Comment by moorepants** [comment]
For a planar problem, the terms you added are zero, no?

**Comment by moorepants** [comment]
$\omega\hat{n}_x \times I\hat{n}_x\hat{n}_x = 0$

**Comment by TJStienstra** [comment]
Yes, you're right forgot to check that. I've also clarified it to the person who noticed it. Thank you!

**Comment by moorepants** [comment]
Great :)

Here is the repo for the online text: https://github.com/moorepants/learn-multibody-dynamics
