### ISSUE TITLE
Tabulate the statistics from last year's exam and homework scores to see % passing and average scores for each

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#67]

**Comment by TJStienstra** [comment]
[grading table.xlsx](https://github.com/moorepants/me41055/files/10487913/grading.table.xlsx)
Simple table showing the grade dependent on the exam and homework scores

**Comment by moorepants** [comment]
Didn't get this done in time to evaluate changes to the grading method, so closing. We can revisit when designing this year's exam if needed.
