### ISSUE TITLE
Setup a simple way to collect the weekly feedback

### ISSUE THREAD

**Issue by moorepants** [moorepants/me41055#72]
**Due Date: Feb 12, 2023**

If we has a simple URL and/or QR code that lead to a google doc/hackpad/hackmd/etherpad/etc then it would be fairly easy for students to get to the space and type some comments. We need to pick a service and setup the tinyurl or similar.

**Comment by moorepants** [comment]
@petrafter could you investigate this for us? The simpler the better.

**Comment by petrafter** [comment]
@moorepants Yes, I will look into this issue!

**Comment by petrafter** [comment]
First setup of feedback that can be collected on a weekly basis: https://forms.gle/aT7MUzRcTncgjL698

**Comment by moorepants** [comment]
Looking good. I guess you could reuse the form each week. We could either use the time stamp to know the week or have a question that asks which week/homework it is. Something like tinyurl.com/mbody-feedback could make it easy to post at the work sessions.

**Comment by petrafter** [comment]
I could update the feedback form weekly and keep track of the results in Excel. The URL is: tinyurl.com/mbd-b-feedback

**Comment by moorepants** [comment]
Each person that are in the 3 rooms will need to remind the people in that room to fill out the form each week. I guess we could also have a reoccurring assignment in brightspace. What do you think?

**Comment by TJStienstra** [comment]
I've added the url at the end of the questions notebook

**Comment by moorepants** [comment]
What is the tiny url?

**Comment by moorepants** [comment]
The url is tinyurl.com/mbd-b-feedback

**Comment by moorepants** [comment]
The first form indicates it is for HW01:

https://docs.google.com/forms/d/e/1FAIpQLSed11T0yM18VkSx2suB5pC6QsfOOQwdSj1Au2h6lAayWG3P8A/viewform

If we want the same tinyurl each week, the form should be for any homework.

Also, if we ask for feedback at the beginning of a worksession, it will be for the prior homework. SO for example the work session on Feb 20, we'd be asking for feedback about HW00 primarily.

**Comment by moorepants** [comment]
@petrafter  Can you make some adjustments to the form so we can use the same one each week and it doesn't refer to the homework.

**Comment by petrafter** [comment]
@moorepants I would like to keep it this way so that I can track to which homework the feedback I receive refers. I will update the form every week with the new homework number as the header. What we need to discuss is when I will switch the feedback form from one homework to the next.

**Comment by moorepants** [comment]
@petrafter Can you change the hour question to ask them "how many hours total did you spend on the course this past week?" and allow for an integer number. It is probably hard to distinguish how much time you spend on the homework vs reading the materials or just pure studying or watch videos. With a number we can see what the 4.5+ actually might mean.

**Comment by petrafter** [comment]
@moorepants I have made the changes you asked for to see how many hours students have spent each week on the course and the homework

**Comment by moorepants** [comment]
Great, thanks!

**Comment by moorepants** [comment]
Given that the students rarely used this and the effort it took to maintain it, we will not do it for 2024.
